const { MongoClient, ServerApiVersion } = require('mongodb');
export default async function handler(req, res) {
  const url = "mongodb+srv://dbuser:<PASSWORD>@cluster0.nthvuuy.mongodb.net/?retryWrites=true&w=majority";
  const client = new MongoClient(url, { useNewUrlParser: true, useUnifiedTopology: true, serverApi: ServerApiVersion.v1 });
  const dbName = 'cinema';

  await client.connect();
  
  const db = client.db(dbName);
  const collection = db.collection('cinemas');
  //const findResult = await collection.find(body).toArray();
  
  
  await collection.insertOne({
    code: "GLI01",
    city: "Gliwice",
    adress: "Piotrowska 11",
    movie_halls:{
      A_01:[
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}]
      ],
      A_02:[
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}]
      ],
      A_03:[
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}]
      ],
      A_04:[
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}]
      ],
      B_01:[
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}]
      ],
      B_02:[
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}]
      ],
      B_03:[
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}]
      ],
      C_01:[
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}]
      ],
      C_02:[
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}]
      ],
      C_03:[
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"},{user:null, type:"premium"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}],
        [{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"},{user:null, type:"normal"}]
      ],
    }
  })
  await client.close()
  res.status(201).json({})
}